lib/web/router.ex
defmodule EspyWeb.Router do
  use EspyWeb, :router

  # -----------------pipeline ----------------

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EspyWeb.Plugs.WebAuthenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug EspyWeb.Plugs.ApiAuthenticate
  end


  pipeline :protected do
    plug EspyWeb.Plugs.Protected
  end


  # ----------------- scope route ----------------

  scope "/", EspyWeb do
    pipe_through [:browser]

    get "/", PageController, :index
    get "/docs", PageController, :docs
    get "/login", PageController, :login

    # oauth
    get "/auth/:provider", AuthController, :request
    get "/auth/:provider/callback", AuthController, :callback
    get "/signout", AuthController, :delete
  end


  # Definitely logged in scope
  scope "/app", EspyWeb do
      pipe_through [:browser, :protected]

      # App controllers
      get "/dashboard", AppController, :dashboard
      get "/new", AppController, :create
      post "/new", AppController, :create
      get "/:id/details", AppController, :show
      put "/:id/details", AppController, :update
      get "/:id/regenerate", AppController, :regenerate
      get "/:id/logs", AppController, :logs
      get "/:id/logs/:page", AppController, :logs

      # Webhook controllers
      get "/:id/webhooks", WebhookController, :list
      post "/:id/webhooks", WebhookController, :create
      get "/:id/webhooks/:webhook_id/delete", WebhookController, :delete
      get "/:id/webhooks/:webhook_id/trigger", WebhookController, :trigger

      # Webhook controllers
      get "/:id/subscriptions", SubscriptionController, :list
      post "/:id/subscriptions", SubscriptionController, :create
      get "/:id/subscriptions/:subscription_id/delete", SubscriptionController, :delete

  end


  scope "/api/v1", EspyWeb, as: :api do
    pipe_through :api

    post "/webhooks", Api.WebhookController, :create
    get "/webhooks", Api.WebhookController, :list
    delete "/webhooks/:webhook_id", Api.WebhookController, :delete

    post "/subscriptions", Api.SubscriptionController, :create
    get "/subscriptions", Api.SubscriptionController, :list
    delete "/subscriptions/:subscription_id", Api.SubscriptionController, :delete


  end


end

lib/web/templates/app/create_app.html.eex
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="/app/dashboard">App</a></li>
    <li class="breadcrumb-item active" aria-current="page">Create App</li>
  </ol>
</nav>




<div class="row">
  <div class="col-6">
    <h4>New App</h4>
    <p>To setup Webhook endpoints and monitor CSCL accounts to receive hooks, you'll have to create an App.</p>
    <p>After creating the App, you can continue setting up your hooks.</p>
  </div>

  <div class="col-6">
    <%= form_for @changeset, "/app/new", [class: "create-app-form"], fn f -> %>

      <div class="form-group">
        <%= input f, :name, using: :text_input , placeholder: "App name" %>
        <%= error_tag f, :name %>
      </div>

      <div class="form-group">
        <%= input f, :url, using: :text_input, placeholder: "App url" %>
        <%= error_tag f, :url %>
      </div>

      <div class="form-group">
        <%= input f, :description, using: :textarea, placeholder: "App description" %>
        <%= error_tag f, :description %>
      </div>

      <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Save</button>

    <% end %>
  </div>
</div>

lib/web/templates/app/dashboard.html.eex
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">App</a></li>
    <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
  </ol>
</nav>


<div class="row">
  <div class="col-md-4 offset-md-8">
    <a href="/app/new" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Create App</a>
  </div>
</div>
</br>
<div class="row">
  <div class="col-12">
    <%= if not Enum.empty?(@apps) do %>
      <table class="table">
        <tbody>
          <%= for app <- @apps do %>
            <tr>
              <td>
                <h3 class="">
                  <%= app.name %>
                </h3>
              </td>
              <td class="">App Id </br><%= app.app_id %></td>
              <td class="">
                <div class="dropdown" >
                  <button class="btn btn-light pull-right" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-ellipsis-v"></i>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="/app/<%= app.app_id %>/webhooks"><i class="fa fa-cog"></i> Manage webhooks</a>
                    <a class="dropdown-item" href="/app/<%= app.app_id %>/subscriptions"><i class="fa fa-eye"></i> Manage subscriptions</a>
                    <a class="dropdown-item" href="/app/<%= app.app_id %>/logs"><i class="fa fa-history"></i> View logs</a>
                  </div>
                </div>
                <a href="/app/<%= app.app_id%>/details" style="margin-right:15px;" class="btn btn-dark pull-right">Details</a>
              </td>

            </tr>
          <% end %>
        </tbody>
      </table>
      <%= else %>

      <div class="ui placeholder segment">
        <div class="alert alert-warning text-center ui icon header">
          <i class="fa fa-exclamation-triangle"></i>
          No Apps have been created yet.
        </div>
      </div>
      <%= end %>

  </div>
</div>

lib/web/templates/app/logs.html.eex
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/app/dashboard">App</a></li>
    <li class="breadcrumb-item"><%= @id %></li>
    <li class="breadcrumb-item active" aria-current="page">Logs</li>
  </ol>
</nav>


<div class="row">
  <div class="col-12">
    <%= if not Enum.empty?(@logs) do %>
       <div class="table-responsive">
      <table class="table">
        <thead>
          <tr><th>ID</th>
            <th>Object ID</th>
            <th>Webhook ID</th>
            <th>URL</th>
            <th>Status</th>
            <th>Response Time</th>
            <th>Retries</th>
            <th class="sorted ascending">Logged at</th>
          </tr>
        </thead>
        <tbody>
          <%= for log <- @logs do %>
            <tr class="
              <%= if div(log.response_status, 100) != 2 do %>
                table-warning
              <% end %>
              ">
              <td >#<%= log.id %></td>
              <td ><a  target="_blank" href="https://bithomp.com/explorer/<%= log.object_id %>"><%= String.slice(log.object_id,  0, 15) %>...</a></td>
              <td ><%= log.webhook.hook_id %></td>
              <td ><%= log.webhook.url %></td>
              <td>
                <%= if div(log.response_status, 100) != 2 do %>
                  <i class="fa-exclamation-circle  fa">&nbsp<%= log.response_status %>
                  <% else %>
                    <span class="text-success"><%= log.response_status %></span>
                <% end %>
              </td>
              <td ><%= log.response_time / 1000000%> sec</td>
              <td ><%= log.retry_count %></td>
              <td ><%= log.inserted_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
      <%= if @count > 20 do %>
        <nav aria-label="navigation">
          <ul class="pagination  justify-content-center">
            <li class="page-item">
              <a href="
                <%= if (@page == 1) do %>
                  #
                  <%= else %>
                  /app/<%= @id %>/logs/<%= @page - 1 %>
                  <%= end %>" class="page-link">Previous
              </a>
            </li>

            <li class="page-item <%= if ( ( @page * 20 ) >= @count ) do %>disabled<%= end %>">
                <a href="/app/<%= @id %>/logs/<%= @page + 1 %>"  class="page-link">Next</a>
            </li>
          </ul>
        </nav>
      <% end %>
    <%= else %>

      <div class="ui placeholder segment">
        <div class="ui icon header">
          <i class="dont icon"></i>
          No logs have been created yet
        </div>
      </div>
    <%= end %>

  </div>
</div>

lib/web/templates/app/show.html.eex
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="/app/dashboard">App</a></li>
		<li class="breadcrumb-item"><%= @app.app_id %></li>
		<li class="breadcrumb-item active" aria-current="page">Details</li>
	</ol>
</nav>


<div class="row">
	<div class="col-3">
		<ul class="nav nav-pills flex-column" aria-orientation="vertical"  role="tablist">
			<li class="nav-item">
				<a class="nav-link active" id="details-tab" data-toggle="tab" href="#details" role="tab" aria-controls="details" aria-selected="true">Details</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" id="keys-tab" data-toggle="tab" href="#keys" role="tab" aria-controls="keys" aria-selected="false">Keys</a>
			</li>
		</ul>
	</div>
	<div class="col-9">

		<div class="tab-content">
			<div class="tab-pane fade show active" id="details" role="tabpanel" aria-labelledby="details-tab">
				<h4>App details</h4>
				<h6>Set your App details for your own administration (and potential review)</h6>
				<hr>
				<%= form_for @changeset, app_path(@conn, :show, @app.app_id), [class: "update-app-form"], fn f -> %>

					<div class="form-group">
						<%= input f, :name, using: :text_input %>
						<%= error_tag f, :name %>
					</div>

					<div class="form-group">
						<%= input f, :url, using: :text_input %>
						<%= error_tag f, :url %>
					</div>

					<div class="form-group">
						<%= input f, :description, using: :textarea %>
						<%= error_tag f, :description %>
					</div>

					<button class="btn float-right btn-primary" type="submit"><i class="fa fa-save"></i> Update</button>

				<% end %>

			</div>
			<div class="tab-pane fade" id="keys" role="tabpanel" aria-labelledby="keys-tab">
				<div class="row">
					<div class="col-12">
						<h4>App API keys</h4>
						<h6 class="sub header">The keys below are required when calling the API.</h6>
						<hr>
						<h5>Consumer API keys</h4>
						<ul class="list-group">
							<li class="list-group-item">
								<h6>API Key</h6>
								<h4><code class="badge badge-secondary"><%= @app.api_key %></code></h4>
							</li>
							<li class="list-group-item">
								<h6>API Secret</h6>
								<h4><code class="badge badge-warning"><%= @app.api_secret %></code></h4>
							</li>
						</ul>
						<br>
						<h4>Regenerate</h4>
						<h6 class="sub header">If your keys have been compromised, you can re-generate your keys. Please update your application after re-generating your keys.</h6>
						<a href="regenerate" class="btn float-right btn-outline-danger" id="regenerate"><i class="fa fa-exclamation-triangle"></i> Regenerate</a>
					</div>
				</div>
			</div>
		</div>


	</div>
</div>