lib/web/router.ex
defmodule EspyWeb.Router do
  use EspyWeb, :router

  # -----------------pipeline ----------------

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EspyWeb.Plugs.WebAuthenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug EspyWeb.Plugs.ApiAuthenticate
  end


  pipeline :protected do
    plug EspyWeb.Plugs.Protected
  end


  # ----------------- scope route ----------------

  scope "/", EspyWeb do
    pipe_through [:browser]

    get "/", PageController, :index
    get "/docs", PageController, :docs
    get "/login", PageController, :login

    # oauth
    get "/auth/:provider", AuthController, :request
    get "/auth/:provider/callback", AuthController, :callback
    get "/signout", AuthController, :delete
  end


  # Definitely logged in scope
  scope "/app", EspyWeb do
      pipe_through [:browser, :protected]

      # App controllers
      get "/dashboard", AppController, :dashboard
      get "/new", AppController, :create
      post "/new", AppController, :create
      get "/:id/details", AppController, :show
      put "/:id/details", AppController, :update
      get "/:id/regenerate", AppController, :regenerate
      get "/:id/logs", AppController, :logs
      get "/:id/logs/:page", AppController, :logs

      # Webhook controllers
      get "/:id/webhooks", WebhookController, :list
      post "/:id/webhooks", WebhookController, :create
      get "/:id/webhooks/:webhook_id/delete", WebhookController, :delete
      get "/:id/webhooks/:webhook_id/trigger", WebhookController, :trigger

      # Webhook controllers
      get "/:id/subscriptions", SubscriptionController, :list
      post "/:id/subscriptions", SubscriptionController, :create
      get "/:id/subscriptions/:subscription_id/delete", SubscriptionController, :delete

  end


  scope "/api/v1", EspyWeb, as: :api do
    pipe_through :api

    post "/webhooks", Api.WebhookController, :create
    get "/webhooks", Api.WebhookController, :list
    delete "/webhooks/:webhook_id", Api.WebhookController, :delete

    post "/subscriptions", Api.SubscriptionController, :create
    get "/subscriptions", Api.SubscriptionController, :list
    delete "/subscriptions/:subscription_id", Api.SubscriptionController, :delete


  end


end

lib/web/controllers/api/v1/subscription_controller.ex
defmodule EspyWeb.Api.SubscriptionController do
  use EspyWeb, :controller

  alias Espy.Gateway.{Webhook, Subscription}

  alias Espy.Watcher.{Cache}

  apigroup("Subscriptions", "")

  api :POST, "/api/v1/subscriptions" do
    title "Subscribes address to app"
    description "Subscribes the provided app all events for the provided address for all transaction types. After activation, all transactions for the requesting address will be sent to the provided webhook id via POST request."
    parameter :address, :string, [description: "Valid XRP address"]
  end

  def create(conn, %{"address" => address}) do
    app = conn.assigns.app

    case Subscription.can_add(app) do
      :can_add ->
	params = %{app_id: app.id, address: address}
	case Subscription.create(params) do
	  {:ok, subscription} ->
	    # set new subscription to Watcher Cache
	    Cache.set(address, app.id)
	    # return response
	    json conn, %{success: true, subscription_id: subscription.subscription_id}
	  {:exist, subscription} ->
	    # return response
	    json conn, %{success: true, subscription_id: subscription.subscription_id}
	  {:error, %Ecto.Changeset{} = changeset } ->
	    conn
	    |> put_status(:unprocessable_entity)
	    |> put_view(EspyWeb.ErrorView)
	    |> render("error.json", changeset: changeset)
	end
      error ->
	conn
	|> put_status(:unprocessable_entity)
	|> json(%{success: false, error: error })
    end

  end

  api :GET, "/api/v1/subscriptions" do
    title "Return all Subscriptions belong to app"
    description "Returns a list of the current Activity type subscriptions."
  end

  def list(conn, _params) do
    app = conn.assigns.app
    subscriptions = Subscription.list_by_app(app.id)
    render(conn, "index.json", app_id: app.app_id, subscriptions: subscriptions)
  end

  api :DELETE, "/api/v1/subscriptions/:subscription_id" do
    title "Delete subscription"
    description "Deactivates subscription(s) for the provided subscription ID  and application for all activities. After deactivation, all events for the requesting subscription_id will no longer be sent to the webhook URL."
    note "The subscription ID can be accessed by making a call to GET /api/v1/subscriptions."
    parameter :subscription_id, :number, [description: "Subscriptions ID to deactivation"]
  end


  def delete(conn, %{"subscription_id" => subscription_id}) do
    app_id = conn.assigns.app.id
    params = %{app_id: app_id, subscription_id: subscription_id}
    case Subscription.delete(params) do
      {:ok, struct} ->
	# Remove address from cache
	Cache.delete(struct.address, app_id)
	# Response
	conn
	|> put_status(:no_content)
	|> json(%{success: true})
      {:error, :not_found} ->
	conn
	|> put_status(:not_found)
	|> json(%{success: false})
      {:error, %Ecto.Changeset{} = changeset } ->
	conn
	|> put_status(:unprocessable_entity)
	|> put_view(EspyWeb.ErrorView)
	|> render("error.json", changeset: changeset)
    end
  end

end

lib/web/controllers/subscription_controller.ex
defmodule EspyWeb.SubscriptionController do
  use EspyWeb, :controller

  alias Espy.Gateway.{Webhook, Subscription, App}

  alias Espy.Watcher.{Cache}

  def list(conn, %{"id" => id }) do
    user_id = conn.assigns.current_user.id
    app = App.get!(id, user_id)
    subscriptions = Subscription.list_by_app(app.id)
    changeset = Subscription.change(%Subscription{})
    render(conn, "list.html", subscriptions: subscriptions, app: app,changeset: changeset)
  end

  def create(conn, %{"subscription" => %{"address" => address}} = params) do
    user = conn.assigns.current_user
    app = App.get!(Map.get(params, "id"), user.id)


    case Subscription.can_add(app) do
      :can_add -> subscription = %{app_id: app.id, address: address}
	case Subscription.create(subscription) do
	  {:ok, subscription} ->
	    # set new subscription to Watcher Cache
	    Cache.set(address, app.id)
	    # return response
	    conn
	    |> put_flash(:info, "Subscription added successfully")
	    |> redirect(to: subscription_path(conn, :list, app.app_id ))
	  {:exist, subscription} ->
	    # return response
	    conn
	    |> put_flash(:info, "Subscription already exist.")
	    |> redirect(to: subscription_path(conn, :list, app.app_id ))
	  {:error, %Ecto.Changeset{} = changeset} ->
	    conn
	    |> put_flash(:error, "Please enter a valid Ripple Address")
	    |> redirect(to: subscription_path(conn, :list, app.app_id ))
	end
      error ->
	conn
	|> put_flash(:error, error)
	|> redirect(to: subscription_path(conn, :list, app.app_id ))
    end

  end

  def delete(conn, %{"id" => id, "subscription_id" => subscription_id}) do
    user_id = conn.assigns.current_user.id
    app = App.get!(id, user_id)
    case Subscription.delete(%{subscription_id: subscription_id, app_id: app.id}) do
      {:ok, struct} ->
	# Remove address from cache
	Cache.delete(struct.address, app.id)
      _ -> true
    end
    redirect(conn, to: subscription_path(conn, :list, app.app_id))
  end

end

lib/web/views/subscription_view.ex
defmodule EspyWeb.SubscriptionView do
  use EspyWeb, :view
  alias EspyWeb.SubscriptionView

end

lib/web/templates/subscription/list.html.eex
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/app/dashboard">App</a></li>
    <li class="breadcrumb-item"><%= @app.app_id %></li>
    <li class="breadcrumb-item active" aria-current="page">Subscription</li>
  </ol>
</nav>

<div class="row">
  <div class="col-12">
    <%= form_for @changeset, subscription_path(@conn, :list, @app.app_id ), [class: "ml-auto"], fn f -> %>
			<h4>Add subscription</h4>
			<h6>To receive HTTP POST calls when a monitored account receives a payment, you need to subscribe to activity for one or more CSCL accounts.</h6>
			<div class="alert alert-primary" role="alert"><strong>Note:</strong> You must have a <a href="<%= webhook_path(@conn, :list, @app.app_id ) %>">registered webhook config</a> to add address, and you must have whitelisted the callback URLs for your app following the setup instructions.</div>
      <div class="form-row align-items-right">
			<div class="col-12">
				<small  class="text-muted">
					Must be a valid CSCL account address, eg. <code>rXXXXXXX....</code>
				</small>
				<%= input f, :address, using: :text_input , label: [class: "sr-only"], input: [placeholder: "CSCL account address"]%>
				<%= error_tag f, :url %>
			</div>
			<div class="col-12 text-right">
	  		<button class="btn btn-primary mb-2" type="submit"><i class="fa fa-save"></i> Add</button>
			</div>
		</div>
    <% end %>
    </br>
  </div>
</div>
</br>
<div class="row">
  <div class="col-12">
    <%= if not Enum.empty?(@subscriptions) do %>
      <table class="table">
	<thead>
	  <tr>
			<th>ID</th>
	    <th>Address</th>
	    <th>Date Added</th>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
	  <%= for subscription <- @subscriptions do %>
	    <tr>
	      <td><code><%= subscription.subscription_id %></code></td>
	      <td><a target="_blank" href="https://bithomp.com/explorer/<%=  subscription.address %>"><%= subscription.address %></a></td>
	      <td ><%= subscription.inserted_at %></td>
	      <td>
					<div class="dropdown" >
						<button class="btn btn-light pull-right" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fa fa-ellipsis-v"></i>
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<a class="dropdown-item delete" href="<%= subscription_path(@conn, :delete, @app.app_id, subscription.subscription_id) %>"><i class="fa fa-trash"></i>&nbsp&nbspDelete</a>
						</div>
					</div>
	      </td>
	    </tr>
	  <% end %>
	</tbody>
				<tfoot>
					<tr>
						<th colspan="100"></th>
					</tr>
				</tfoot>
      </table>
    <% else %>
      <hr>
      <p class="alert alert-warning text-center mt-3">No subscriptions added yet</p>
    <% end %>
  </div>
</div>